#! /usr/bin/env node
'use string';

const { enc } = require('./index');

try {
    if (process.argv.length != 3) {
		throw new Error(`Usage: ${process.argv[1]} <json-data>`);
	}
	let d = JSON.parse(process.argv[2]);
	console.log(Array.from(enc(d)).map((x)=>(x.toString(16).padStart(2, '0'))).join(' '));
} catch (e) {
	throw e;
}
